# Site settings
title: Career Catalogue
description: A collection of career resources
baseurl: "/career-catalogue"
url: "https://howellsryan.github.io"

# Build settings
markdown: kramdown
theme: minima  # Using minima as the base theme
sass:
  sass_dir: _sass
  style: compressed

kramdown:
  auto_ids: false
